version: '3.9'

services:

  bibliotheca.backend:
    image: ${DOCKER_REGISTRY-}bibliothecabackend
    build:
      context: .
      dockerfile: Bibliotheca.Backend/Dockerfile
    environment:
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_URL: "server=database_bibliotheca;username=${DATABASE_USER};password=${DATABASE_PASSWORD};database=${DATABASE_NAME}"
    ports:
        - "8080:8080"
    depends_on:
        - db


  bibliotheca.frontend:
    build:
      context: Bibliotheca.Frontend/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: dev
    ports:
      - "4200:4200"

  db:
    image: postgres
    container_name: database_bibliotheca
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
        - "5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
